#!/usr/bin/env python3
"""
Read binary phase space file (v2, 60 bytes per photon) generated by Geant4 Cherenkov simulation.
"""

import os
import numpy as np
import sys

BYTES_PER_PHOTON = 60

# v2 compound dtype, explicit little-endian
PHSP_DTYPE = np.dtype([
    ("initX", "<f4"), ("initY", "<f4"), ("initZ", "<f4"),
    ("initDirX", "<f4"), ("initDirY", "<f4"), ("initDirZ", "<f4"),
    ("finalX", "<f4"), ("finalY", "<f4"), ("finalZ", "<f4"),
    ("finalDirX", "<f4"), ("finalDirY", "<f4"), ("finalDirZ", "<f4"),
    ("finalEnergy", "<f4"),
    ("event_id", "<u4"),
    ("track_id", "<i4"),
])


def _path_header(phsp_file):
    """Same directory, same basename, .header."""
    base = os.path.splitext(phsp_file)[0]
    return base + ".header"


def _validate_header_if_present(phsp_file):
    """
    If .header exists, validate format_version 2 and bytes_per_photon 60.
    Raises ValueError if header exists and is not v2.
    """
    header_path = _path_header(phsp_file)
    if not os.path.isfile(header_path):
        return
    format_version = None
    bytes_per_photon = None
    with open(header_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            for sep in (":", "="):
                if sep in line:
                    k, v = line.split(sep, 1)
                    k, v = k.strip().lower(), v.strip()
                    if "format_version" in k or k == "format_version":
                        try:
                            format_version = int(float(v))
                        except ValueError:
                            pass
                    elif "bytes_per_photon" in k or k == "bytes_per_photon":
                        try:
                            bytes_per_photon = int(float(v))
                        except ValueError:
                            pass
                    break
    if format_version is not None and format_version != 2:
        raise ValueError(
            f"Header format_version={format_version} is not v2; "
            f"only v2 (60 bytes per photon) is supported"
        )
    if bytes_per_photon is not None and bytes_per_photon != 60:
        raise ValueError(
            f"Header bytes_per_photon={bytes_per_photon} is not 60; "
            f"only v2 (60 bytes per photon) is supported"
        )


def read_binary_phsp(phsp_file):
    """
    Read binary phase space file (v2, 60 bytes per photon).

    File format (15 fields, 60 bytes per photon, little-endian):
      initX, initY, initZ [cm]
      initDirX, initDirY, initDirZ
      finalX, finalY, finalZ [cm]
      finalDirX, finalDirY, finalDirZ
      finalEnergy [microeV]
      event_id (uint32, G4Event::GetEventID())
      track_id (int32, G4Track::GetTrackID(); -1 = unknown)

    Validation:
      - file_size % 60 != 0 -> ValueError
      - If .header exists: format_version must be 2, bytes_per_photon must be 60

    Returns:
        Structured numpy array with PHSP_DTYPE (event_id, track_id included)
    """
    print(f"Reading binary file (v2, 60B): {phsp_file}")

    file_size = os.path.getsize(phsp_file)
    if file_size % BYTES_PER_PHOTON != 0:
        raise ValueError(
            f"PHSP file size {file_size} is not divisible by {BYTES_PER_PHOTON}; "
            f"expected v2 format (60 bytes per photon)"
        )

    _validate_header_if_present(phsp_file)

    data = np.fromfile(phsp_file, dtype=PHSP_DTYPE)
    n_photons = len(data)

    print(f"Total photons: {n_photons:,}")
    print(f"File size: {file_size / (1024**3):.2f} GB")

    return data


def extract_fields(data):
    """
    Extract individual fields from structured array.

    Returns:
        Dictionary with field names as keys (including event_id, track_id)
    """
    return {
        "InitialX": data["initX"],
        "InitialY": data["initY"],
        "InitialZ": data["initZ"],
        "InitialDirX": data["initDirX"],
        "InitialDirY": data["initDirY"],
        "InitialDirZ": data["initDirZ"],
        "FinalX": data["finalX"],
        "FinalY": data["finalY"],
        "FinalZ": data["finalZ"],
        "FinalDirX": data["finalDirX"],
        "FinalDirY": data["finalDirY"],
        "FinalDirZ": data["finalDirZ"],
        "FinalEnergy": data["finalEnergy"],
        "event_id": data["event_id"],
        "track_id": data["track_id"],
    }


def show_statistics(data):
    """Show basic statistics of the data"""
    fields = extract_fields(data)

    print("\n" + "=" * 60)
    print("Data Statistics")
    print("=" * 60)

    print("\nInitial Position (cm):")
    print(f"  X: [{fields['InitialX'].min():.3f}, {fields['InitialX'].max():.3f}]")
    print(f"  Y: [{fields['InitialY'].min():.3f}, {fields['InitialY'].max():.3f}]")
    print(f"  Z: [{fields['InitialZ'].min():.3f}, {fields['InitialZ'].max():.3f}]")

    print("\nFinal Position (cm):")
    print(f"  X: [{fields['FinalX'].min():.3f}, {fields['FinalX'].max():.3f}]")
    print(f"  Y: [{fields['FinalY'].min():.3f}, {fields['FinalY'].max():.3f}]")
    print(f"  Z: [{fields['FinalZ'].min():.3f}, {fields['FinalZ'].max():.3f}]")

    print("\nEnergy (microeV):")
    print(f"  Min: {fields['FinalEnergy'].min():.3f}")
    print(f"  Max: {fields['FinalEnergy'].max():.3f}")
    print(f"  Mean: {fields['FinalEnergy'].mean():.3f}")
    print(f"  Median: {np.median(fields['FinalEnergy']):.3f}")

    print("\nevent_id range:", fields["event_id"].min(), "-", fields["event_id"].max())
    print("track_id range:", fields["track_id"].min(), "-", fields["track_id"].max())

    print("\nFirst 5 photons:")
    print("  InitialX   InitialY   InitialZ   FinalX     FinalY     FinalZ     Energy     event_id  track_id")
    for i in range(min(5, len(data))):
        r = data[i]
        print(
            f"  {r['initX']:9.3f}  {r['initY']:9.3f}  {r['initZ']:9.3f}  "
            f"{r['finalX']:9.3f}  {r['finalY']:9.3f}  {r['finalZ']:9.3f}  "
            f"{r['finalEnergy']:9.1f}  {r['event_id']:9d}  {r['track_id']:9d}"
        )


if __name__ == "__main__":
    if len(sys.argv) < 2:
        phsp_file = "output/cherenkov_photons_full.phsp"
    else:
        phsp_file = sys.argv[1]

    data = read_binary_phsp(phsp_file)
    show_statistics(data)

    print("\n" + "=" * 60)
    print("Quick plotting example:")
    print("=" * 60)
    print("""
import matplotlib.pyplot as plt

fields = extract_fields(data)

# Plot initial positions
plt.figure(figsize=(10, 4))
plt.subplot(121)
plt.hist2d(fields['InitialX'], fields['InitialY'], bins=100, cmap='hot')
plt.xlabel('X (cm)')
plt.ylabel('Y (cm)')
plt.title('Initial Position')
plt.colorbar(label='Count')

# Plot energy distribution
plt.subplot(122)
plt.hist(fields['FinalEnergy'], bins=100, alpha=0.7)
plt.xlabel('Energy (microeV)')
plt.ylabel('Count')
plt.title('Energy Distribution')
plt.tight_layout()
plt.show()
""")
