#!/usr/bin/env python3
"""
Read binary phase space file generated by Geant4 Cherenkov simulation
"""

import numpy as np
import sys

def read_binary_phsp(phsp_file):
    """
    Read binary phase space file
    
    File format: 13 float32 values per photon (52 bytes per photon):
      0: InitialX [cm]
      1: InitialY [cm]
      2: InitialZ [cm]
      3: InitialDirX
      4: InitialDirY
      5: InitialDirZ
      6: FinalX [cm]
      7: FinalY [cm]
      8: FinalZ [cm]
      9: FinalDirX
     10: FinalDirY
     11: FinalDirZ
     12: FinalEnergy [microeV]
    
    Returns:
        numpy array of shape (n_photons, 13)
    """
    print(f"Reading binary file: {phsp_file}")
    
    # Read binary data
    data = np.fromfile(phsp_file, dtype='float32')
    
    # Reshape to (n_photons, 13)
    n_values = len(data)
    if n_values % 13 != 0:
        print(f"WARNING: File has {n_values} values, not divisible by 13")
        # Truncate to multiple of 13
        n_values = (n_values // 13) * 13
        data = data[:n_values]
    
    data = data.reshape(-1, 13)
    n_photons = data.shape[0]
    
    print(f"Total photons: {n_photons:,}")
    print(f"File size: {n_values * 4 / (1024**3):.2f} GB")
    
    return data


def extract_fields(data):
    """
    Extract individual fields from data array
    
    Returns:
        Dictionary with field names as keys
    """
    return {
        'InitialX': data[:, 0],
        'InitialY': data[:, 1],
        'InitialZ': data[:, 2],
        'InitialDirX': data[:, 3],
        'InitialDirY': data[:, 4],
        'InitialDirZ': data[:, 5],
        'FinalX': data[:, 6],
        'FinalY': data[:, 7],
        'FinalZ': data[:, 8],
        'FinalDirX': data[:, 9],
        'FinalDirY': data[:, 10],
        'FinalDirZ': data[:, 11],
        'FinalEnergy': data[:, 12]  # in microeV
    }


def show_statistics(data):
    """Show basic statistics of the data"""
    fields = extract_fields(data)
    
    print("\n" + "="*60)
    print("Data Statistics")
    print("="*60)
    
    print("\nInitial Position (cm):")
    print(f"  X: [{fields['InitialX'].min():.3f}, {fields['InitialX'].max():.3f}]")
    print(f"  Y: [{fields['InitialY'].min():.3f}, {fields['InitialY'].max():.3f}]")
    print(f"  Z: [{fields['InitialZ'].min():.3f}, {fields['InitialZ'].max():.3f}]")
    
    print("\nFinal Position (cm):")
    print(f"  X: [{fields['FinalX'].min():.3f}, {fields['FinalX'].max():.3f}]")
    print(f"  Y: [{fields['FinalY'].min():.3f}, {fields['FinalY'].max():.3f}]")
    print(f"  Z: [{fields['FinalZ'].min():.3f}, {fields['FinalZ'].max():.3f}]")
    
    print("\nEnergy (microeV):")
    print(f"  Min: {fields['FinalEnergy'].min():.3f}")
    print(f"  Max: {fields['FinalEnergy'].max():.3f}")
    print(f"  Mean: {fields['FinalEnergy'].mean():.3f}")
    print(f"  Median: {np.median(fields['FinalEnergy']):.3f}")
    
    print("\nFirst 5 photons:")
    print("  InitialX   InitialY   InitialZ   FinalX     FinalY     FinalZ     Energy")
    for i in range(min(5, len(data))):
        print(f"  {data[i,0]:9.3f}  {data[i,1]:9.3f}  {data[i,2]:9.3f}  "
              f"{data[i,6]:9.3f}  {data[i,7]:9.3f}  {data[i,8]:9.3f}  {data[i,12]:9.1f}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        phsp_file = 'output/cherenkov_photons_full.phsp'
    else:
        phsp_file = sys.argv[1]
    
    # Read data
    data = read_binary_phsp(phsp_file)
    
    # Show statistics
    show_statistics(data)
    
    print("\n" + "="*60)
    print("Quick plotting example:")
    print("="*60)
    print("""
import matplotlib.pyplot as plt

# Extract fields
fields = extract_fields(data)

# Plot initial positions
plt.figure(figsize=(10, 4))
plt.subplot(121)
plt.hist2d(fields['InitialX'], fields['InitialY'], bins=100, cmap='hot')
plt.xlabel('X (cm)')
plt.ylabel('Y (cm)')
plt.title('Initial Position')
plt.colorbar(label='Count')

# Plot energy distribution
plt.subplot(122)
plt.hist(fields['FinalEnergy'], bins=100, alpha=0.7)
plt.xlabel('Energy (microeV)')
plt.ylabel('Count')
plt.title('Energy Distribution')
plt.tight_layout()
plt.show()
""")
